import { defineConfig, loadEnv, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";
import path from "node:path";
import { readFileSync } from "node:fs";

// Pull the package.json version once at config load and expose it to the app
// via `import.meta.env.VITE_APP_VERSION`. Avoids importing package.json into
// the runtime bundle.
const pkg = JSON.parse(readFileSync(path.resolve(__dirname, "package.json"), "utf8"));

// ---- V15 — Firebase Messaging service worker generator -------------------
// Builds /firebase-messaging-sw.js with the Firebase config inlined so the
// worker can initialise itself without the main app bundle. Serves the file
// during `vite dev` (middleware) and emits it as an asset during `build`.
//
// Firebase values come from env (same ones the app already reads). We don't
// ship a hand-maintained file in public/ — it would go stale and leak dev
// config into prod.
//
// N-2.1: The compat SDK is self-hosted under /vendor/firebase/. Loading
// from gstatic.com worked but any browser-side filter (privacy extension,
// corporate DNS) can silently block it — and then the SW simply dies at
// importScripts with no way for the app to know. Our own origin always
// resolves.
function firebaseMessagingSw(
  env: Record<string, string>,
): Plugin {
  const VENDOR_FILES = [
    "firebase-app-compat.js",
    "firebase-messaging-compat.js",
  ];
  // Resolved at plugin construction — path inside the app's node_modules.
  const vendorSrcDir = path.resolve(__dirname, "node_modules/firebase");

  const buildSource = (): string => `/* AUTO-GENERATED by vite.config.ts. Do not edit — rebuild instead. */
importScripts("./vendor/firebase/firebase-app-compat.js");
importScripts("./vendor/firebase/firebase-messaging-compat.js");

firebase.initializeApp({
  apiKey: ${JSON.stringify(env.VITE_FIREBASE_API_KEY ?? "")},
  authDomain: ${JSON.stringify(env.VITE_FIREBASE_AUTH_DOMAIN ?? "")},
  projectId: ${JSON.stringify(env.VITE_FIREBASE_PROJECT_ID ?? "")},
  storageBucket: ${JSON.stringify(env.VITE_FIREBASE_STORAGE_BUCKET ?? "")},
  messagingSenderId: ${JSON.stringify(env.VITE_FIREBASE_MESSAGING_SENDER_ID ?? "")},
  appId: ${JSON.stringify(env.VITE_FIREBASE_APP_ID ?? "")},
});

const messaging = firebase.messaging();

// Background push (app closed or in another tab) — render the notification
// ourselves using the payload. Tag by taskId so a second push on the same
// thread collapses onto the first on iOS / Android native notification UIs.
messaging.onBackgroundMessage((payload) => {
  // Data-only payload: title/body jsou v payload.data, ne v payload.notification.
  // (Pokud by v budoucnu někdo změnil server na notification-based, padneme
  //  zpět na tu cestu — proto dvoustupňový fallback.)
  const data  = (payload && payload.data) || {};
  const title = data.title
                || (payload && payload.notification && payload.notification.title)
                || "Chytrý dům";
  const body  = data.body
                || (payload && payload.notification && payload.notification.body)
                || "";

  // App badge na ikonce plochy (iOS 16.4+ / Chrome PWA / macOS Safari PWA).
  // Minimální verze — jen puntík ("je tam něco nového"), bez čísla.
  // Počet by vyžadoval tracking v IndexedDB; pro MVP stačí flag.
  // Clear hodí client-side na window visibility change (useAppBadge hook).
  if (typeof navigator !== "undefined" && "setAppBadge" in navigator) {
    try {
      navigator.setAppBadge(1).catch(function() { /* noop */ });
    } catch (_) { /* noop */ }
  }

  // iOS Safari Web Push má dva dopady, kvůli kterým notifikace tiše padá:
  //   (a) ikona musí být raster (PNG/JPEG), SVG Apple nerenderuje.
  //   (b) showNotification vrací Promise — FCM SDK ji interně wraapi
  //       do event.waitUntil, ale jen pokud ji z handleru vrátíme.
  //       Bez return iOS SW někdy skončí dřív, než notifikace fakt vyrenderuje.
  return self.registration.showNotification(title, {
    body,
    icon: "/icon-192.png",
    badge: "/icon-192.png",
    data,
    tag: data.taskId ? ("task-" + data.taskId) : undefined,
  });
});

// Deep-link click handler — reuse an already-open window if we find one,
// otherwise spawn a new tab. Target path is passed via payload.data.url.
self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const url = (event.notification.data && event.notification.data.url) || "/";
  event.waitUntil((async () => {
    const all = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
    for (const client of all) {
      if ("focus" in client) {
        try { await client.focus(); } catch (_) {}
        try { client.postMessage({ type: "NAVIGATE", url }); } catch (_) {}
        return;
      }
    }
    if (self.clients.openWindow) {
      await self.clients.openWindow(url);
    }
  })());
});
`;

  return {
    name: "firebase-messaging-sw",
    configureServer(server) {
      // Dev: serve the generated SW on demand + proxy the self-hosted
      // Firebase compat files out of node_modules. Vite doesn't normally
      // expose node_modules to the browser, but the SW import paths are
      // resolved as same-origin URLs, so we need to serve them ourselves.
      server.middlewares.use((req, res, next) => {
        if (req.url === "/firebase-messaging-sw.js") {
          res.setHeader("Content-Type", "application/javascript; charset=utf-8");
          res.setHeader("Service-Worker-Allowed", "/");
          res.end(buildSource());
          return;
        }
        const vendorPrefix = "/vendor/firebase/";
        if (req.url && req.url.startsWith(vendorPrefix)) {
          const file = req.url.slice(vendorPrefix.length).split("?")[0];
          if (VENDOR_FILES.includes(file)) {
            try {
              const content = readFileSync(path.join(vendorSrcDir, file));
              res.setHeader("Content-Type", "application/javascript; charset=utf-8");
              res.end(content);
              return;
            } catch (e) {
              // fall through to 404
              console.warn("firebaseMessagingSw: failed to read", file, e);
            }
          }
        }
        next();
      });
    },
    generateBundle() {
      this.emitFile({
        type: "asset",
        fileName: "firebase-messaging-sw.js",
        source: buildSource(),
      });
      for (const file of VENDOR_FILES) {
        const content = readFileSync(path.join(vendorSrcDir, file), "utf-8");
        this.emitFile({
          type: "asset",
          fileName: `vendor/firebase/${file}`,
          source: content,
        });
      }
    },
  };
}

export default defineConfig(({ mode }) => {
  // loadEnv picks up .env, .env.local, .env.<mode>[.local] + process.env. We
  // keep the "" prefix so VITE_* and any other prefix the build script sets
  // (OPE_VITE_* in CI) are both visible to the SW generator.
  const env = loadEnv(mode, process.cwd(), "");

  return {
  // Base path for sub-directory hosting (GitHub Pages). Defaults to / for Netlify / local dev.
  base: process.env.VITE_BASE_PATH || "/",
  define: {
    "import.meta.env.VITE_APP_VERSION": JSON.stringify(pkg.version),
  },
  plugins: [
    // V12.2 — emit dist/version.json so the running app can poll for new
    // deploys and force-reload when it detects a version mismatch.
    {
      name: "emit-version-json",
      apply: "build",
      generateBundle() {
        this.emitFile({
          type: "asset",
          fileName: "version.json",
          source: JSON.stringify({ version: pkg.version, built: new Date().toISOString() }) + "\n",
        });
      },
    },
    firebaseMessagingSw(env),
    react(),
    VitePWA({
      registerType: "autoUpdate",
      // PWA plugin must know the deploy base so service worker scope + start_url
      // resolve correctly on sub-path hosts (GitHub Pages /clever-house/).
      base: process.env.VITE_BASE_PATH || "/",
      workbox: {
        // Navigate fallback must be scoped to the base path or SPA deep links 404.
        navigateFallback: (process.env.VITE_BASE_PATH || "/") + "index.html",
        globPatterns: ["**/*.{js,css,html,svg,woff2,woff,ttf,png}"],
        // Never precache Firebase Storage / Firestore — always fresh from network
        navigateFallbackDenylist: [
          /^\/__\/.*/,  // Firebase hosting internals
          /firebaseio\.com/,
          /googleapis\.com/,
          /firebasestorage\.googleapis\.com/,
        ],
        runtimeCaching: [
          {
            // Firebase Storage images — stale-while-revalidate for snappy thumbnails
            urlPattern: /^https:\/\/firebasestorage\.googleapis\.com\/.*/,
            handler: "StaleWhileRevalidate",
            options: {
              cacheName: "firebase-storage-images",
              expiration: {
                maxEntries: 200,
                maxAgeSeconds: 60 * 60 * 24 * 30, // 30d
              },
            },
          },
          {
            // Inter font — cache forever
            urlPattern: /\/fonts\/.*\.woff2?$/,
            handler: "CacheFirst",
            options: {
              cacheName: "fonts",
              expiration: { maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 * 365 },
            },
          },
        ],
      },
      includeAssets: ["favicon.svg", "icon-192.svg", "icon-192.png", "icon-512.svg", "apple-touch-icon.png"],
      manifest: {
        name: "Chytrý dům na vsi",
        short_name: "Chytrý dům",
        description:
          "Záznamník nápadů, otázek a rozhodnutí pro stavbu domu.",
        start_url: ".",
        scope: "./",
        display: "standalone",
        orientation: "portrait",
        theme_color: "#5E5D3F",       // olive-700 (accent-default)
        background_color: "#F9F7F3",  // stone-50 (bg-default light)
        lang: "cs-CZ",
        dir: "ltr",
        categories: ["productivity", "utilities"],
        icons: [
          {
            src: "icon-192.svg",
            sizes: "192x192",
            type: "image/svg+xml",
            purpose: "any",
          },
          {
            src: "icon-512.svg",
            sizes: "512x512",
            type: "image/svg+xml",
            purpose: "any",
          },
          {
            src: "icon-maskable-512.svg",
            sizes: "512x512",
            type: "image/svg+xml",
            purpose: "maskable",
          },
        ],
      },
    }),
  ],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  server: {
    host: true,
    port: 5173,
  },
  };
});
