import {
  getMessaging,
  getToken,
  isSupported as fcmIsSupported,
  onMessage,
  type MessagePayload,
  type Messaging,
} from "firebase/messaging";
import { app } from "./firebase";
import {
  getOrCreateDeviceId,
  registerDevice,
  unregisterDevice,
} from "./notifications";
import type { NotificationDevice } from "@/types";

/**
 * V15 — browser-side Firebase Cloud Messaging. Thin wrapper around the
 * modular FCM SDK:
 *   - isMessagingSupported()          — guard for old browsers
 *   - requestPermissionAndRegister()  — one-shot permission + token fetch + Firestore write
 *   - unregisterCurrentDevice()       — logout / sign-out-everywhere path
 *   - subscribeForegroundMessages()   — onMessage wrapper for in-app toast
 *
 * Service worker lives at /firebase-messaging-sw.js and is generated by the
 * Vite plugin in vite.config.ts (see firebaseMessagingSw).
 */

// ---------- Feature detection ----------

let cachedSupport: Promise<boolean> | null = null;

/** Async feature check — caches the answer for the session. Returns false
 *  in anything without Notification API, Push API, SW registration, or
 *  FCM's own `isSupported` gate (notably iOS < 16.4 Safari in-browser). */
export function isMessagingSupported(): Promise<boolean> {
  if (cachedSupport) return cachedSupport;
  cachedSupport = (async () => {
    if (typeof window === "undefined") return false;
    if (typeof Notification === "undefined") return false;
    if (!("serviceWorker" in navigator)) return false;
    try {
      return await fcmIsSupported();
    } catch {
      return false;
    }
  })();
  return cachedSupport;
}

// ---------- Messaging instance ----------

let cachedMessaging: Messaging | null = null;

async function getMessagingInstance(): Promise<Messaging | null> {
  if (cachedMessaging) return cachedMessaging;
  if (!(await isMessagingSupported())) return null;
  cachedMessaging = getMessaging(app);
  return cachedMessaging;
}

// ---------- Platform detection ----------

/** Coarse UA sniff — good enough for tagging registrations with a
 *  platform hint. Not used for feature gating (that's isMessagingSupported). */
export function detectPlatform(): NotificationDevice["platform"] {
  if (typeof navigator === "undefined") return "desktop";
  const ua = navigator.userAgent || "";
  if (/iphone|ipad|ipod/i.test(ua)) return "ios";
  if (/android/i.test(ua)) return "android";
  return "desktop";
}

// ---------- Permission + token flow ----------

export type RegistrationResult =
  | { status: "granted"; token: string; deviceId: string }
  | { status: "denied" }
  | { status: "default" }
  | { status: "unsupported" }
  | { status: "no_token" }
  | { status: "error"; error: unknown };

/**
 * One-shot flow: ask for permission → get FCM token → write device doc.
 * Idempotent — calling it twice from a "granted" state just refreshes the
 * token in Firestore. Safe to call from a useEffect on login.
 *
 * Returns a structured result so the UI can branch (show "denied" help
 * message, retry on "no_token", etc.). Never throws — caller can assume
 * status enum tells the whole story.
 */
export async function requestPermissionAndRegister(
  uid: string,
): Promise<RegistrationResult> {
  try {
    const supported = await isMessagingSupported();
    if (!supported) return { status: "unsupported" };

    // Notification.permission short-circuits if already set: "granted" /
    // "denied" returns immediately; "default" triggers the OS prompt. On
    // iOS the prompt only works when called from a user gesture — callers
    // must wire this behind a button click, not on mount.
    const permission = await Notification.requestPermission();
    if (permission !== "granted") {
      return { status: permission as "denied" | "default" };
    }

    const messaging = await getMessagingInstance();
    if (!messaging) return { status: "unsupported" };

    const vapidKey = import.meta.env.VITE_FIREBASE_VAPID_KEY;
    if (!vapidKey) {
      console.warn("VITE_FIREBASE_VAPID_KEY is missing — push disabled");
      return { status: "unsupported" };
    }

    // Get (or refresh) the FCM token. Passing the existing SW registration
    // keeps this token tied to the worker we generate in vite.config.ts.
    const swReg = await navigator.serviceWorker.getRegistration(
      "/firebase-messaging-sw.js",
    );
    const token = await getToken(messaging, {
      vapidKey,
      serviceWorkerRegistration: swReg,
    });
    if (!token) return { status: "no_token" };

    const deviceId = getOrCreateDeviceId();
    await registerDevice({
      uid,
      deviceId,
      token,
      platform: detectPlatform(),
      userAgent: typeof navigator !== "undefined" ? navigator.userAgent : "",
    });

    return { status: "granted", token, deviceId };
  } catch (error) {
    console.error("requestPermissionAndRegister failed", error);
    return { status: "error", error };
  }
}

/**
 * Drop this browser's registration from the user's account. Called on
 * logout (and when the user explicitly flips the master switch off). Does
 * NOT revoke the permission itself — that's only user-driven in iOS
 * Settings. But future pushes won't have a token to target.
 */
export async function unregisterCurrentDevice(uid: string): Promise<void> {
  try {
    const deviceId = getOrCreateDeviceId();
    await unregisterDevice({ uid, deviceId });
  } catch (err) {
    console.error("unregisterCurrentDevice failed", err);
  }
}

// ---------- Foreground messages ----------

/**
 * When the app is open and focused, FCM delivers the payload via onMessage
 * instead of popping a native notification (iOS/Android design decision).
 * We expose the stream so a UI layer can show an in-app toast / inbox /
 * whatever feels right. Unsubscribe on component unmount.
 */
export function subscribeForegroundMessages(
  cb: (payload: MessagePayload) => void,
): () => void {
  let unsub: (() => void) | null = null;
  let cancelled = false;
  (async () => {
    const messaging = await getMessagingInstance();
    if (!messaging || cancelled) return;
    unsub = onMessage(messaging, cb);
  })();
  return () => {
    cancelled = true;
    if (unsub) unsub();
  };
}

// ---------- Service worker messages ----------

/**
 * The SW posts { type: "NAVIGATE", url } when the user clicks a background
 * notification and a window was already open. This helper subscribes to
 * those messages so the app router can react (soft navigation) instead of
 * the SW doing a hard reload.
 */
export function subscribeSwNavigate(
  cb: (url: string) => void,
): () => void {
  if (typeof navigator === "undefined" || !navigator.serviceWorker) {
    return () => {};
  }
  const listener = (event: MessageEvent) => {
    const data = event.data as { type?: string; url?: string } | null;
    if (data && data.type === "NAVIGATE" && typeof data.url === "string") {
      cb(data.url);
    }
  };
  navigator.serviceWorker.addEventListener("message", listener);
  return () => {
    navigator.serviceWorker.removeEventListener("message", listener);
  };
}
